apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodeprep.fullname" . }}-controller
  namespace: {{ include "nodeprep.namespace" . }}
  labels:
    {{- include "nodeprep.controllerLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodeprep.fullname" . }}-agent
  namespace: {{ include "nodeprep.namespace" . }}
  labels:
    {{- include "nodeprep.agentLabels" . | nindent 4 }}
